key,default_value
userAgent,"aws-cli/1.16.19 Python/2.7.15+ Linux/4.18.0-kali1-amd64 botocore/1.12.9"
eventID,"bca4c684-87ff-4330-8694-013630c601630c"
errorMessage,"User: arn:aws:iam::811596193553:user/backup is not authorized to perform: dynamodb:ListBackups on resource: *"
userIdentity_type,"IAMUser"
userIdentity_principalId,"AIDA9BO36HFBHKGJAO9C1"
userIdentity_arn,"arn:aws:iam::811596193553:user/backup"
userIdentity_accountId,"811596193553"
userIdentity_accessKeyId,"AKIA01U43UX3RBRDXF4Q"
userIdentity_userName,"backup"
eventType,"AwsApiCall"
errorCode,"AccessDenied"
sourceIPAddress,"89.253.73.252"
eventName,"ListBackups"
eventSource,"dynamodb.amazonaws.com"
recipientAccountId,"811596193553"
requestParameters,"None"
awsRegion,"us-west-1"
requestID,"LMQOEDRR478RS3J01CVS7NFM3RVV4KQNSO5AEMVJF66Q9ASUAAJG"
responseElements,"None"
eventVersion,"1.05"
eventTime,"2018-09-27T07:44:51Z"
